### PR TITLE
Port Succo's fix to cache decodeHooks

### PR DESCRIPTION
**Pull request by cedric-cordenier**
Like @Succo we are seeing a big performance hit from typedDecodeHook being called repeatedly.

Fixes #33

### CODE REVIEW

**Comment by edanko** [comment]
This is awesome! 3x improvement on a real life code.
`
BenchmarkBefore-12            9506            144817 ns/op            3095 B/op         55 allocs/op
BenchmarkAfter-12           24036             51131 ns/op            3059 B/op         54 allocs/op
`

**Comment by cedric-cordenier** [comment]
@sagikazarmark Any chance you could help us get this reviewed and merged? It'd be really great to get this fix upstream so we can stop relying on a fork. Thanks!

**Comment by cedric-cordenier** [comment]
Thanks @sagikazarmark, greatly appreciated! 🙏 

The original PR is here: https://github.com/mitchellh/mapstructure/pull/324

I've just merged main back into my branch. Let me know if you need me to do anything else :)

**Review by sagikazarmark — APPROVED** [review]
Thanks!

**Pull request merged**
