### PR TITLE
Add an example showing how to use a DecodeHookFunc to parse a custom …

### PR DESCRIPTION
**Pull request by carlohamalainen**
…field.

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Thanks @carlohamalainen

I'm not entirely sure what's going on with CI. Would you mind rebasing and force pushing to trigger it again?

Thanks!

**Comment by carlohamalainen** [comment]
> Thanks @carlohamalainen
> 
> I'm not entirely sure what's going on with CI. Would you mind rebasing and force pushing to trigger it again?

Done: merged my two commits, merged main, push force.

**Comment by carlohamalainen** [comment]
@sagikazarmark  Any idea why the workflow won't run the lint and tests?

**Comment by sagikazarmark** [comment]
@carlohamalainen looks like there are some lint violations. Can you please run `golangci-lint run --fix`?

**Review by sagikazarmark — APPROVED** [review]

**Pull request merged**
